name: vendor
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0
  intl: ^0.16.1
  percent_indicator: ^2.1.5
  flutter_phoenix: ^0.1.0
  flutter_bloc: ^6.0.1
  grouped_buttons: ^1.0.4
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.4+1
  flutter_local_notifications: ^2.0.0
  firebase_messaging: ^7.0.2
  shared_preferences: ^0.5.10
  toast: ^0.1.5
  http: ^0.12.2
  image_picker: ^0.6.7+11
  file_picker: ^2.1.7
  shimmer_animation: ^0.1.1
  flutter_html: ^1.1.1
  slide_popup_dialog: ^0.0.2
  whatsapp_unilink: ^1.0.0+1
  url_launcher: ^5.7.10
  share: ^0.6.5+4
  cached_network_image: ^2.5.0
  infinite_scroll_pagination: ^2.3.0
  flutter_barcode_scanner: ^1.0.2
#  esc_pos_printer: ^3.1.3
  esc_pos_bluetooth: ^0.2.8
#  flutter_bluetooth_basic: ^0.1.5
  esc_pos_utils: any
  image: ^2.1.4
  focused_menu: ^1.0.2
  firebase_dynamic_links: ^0.6.3
  date_picker_timeline: ^1.2.1
  package_info: ^0.4.3+4
#  bluetoothonoff: ^0.1.0
  bluetooth_enable: ^0.1.1
  pdf: ^2.1.0
  flutter_full_pdf_viewer: ^1.0.6
  path_provider: ^1.6.27
  printing: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5
  change_app_package_name: ^0.1.2

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"


flutter:
  uses-material-design: true
  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans-Regular.ttf
        - asset: fonts/ProductSans-Bold.ttf

  assets:
    - assets/
    - assets/Logos/
    - assets/ProductImages/
    - assets/fonts/OpenSans-Regular.ttf
    - assets/fonts/OpenSans-Bold.ttf
    - assets/fonts/OpenSans-Italic.ttf
    - assets/fonts/OpenSans-BoldItalic.ttf
